name: "Deploy"
on:
  pull_request:
  push:
jobs:
  deploy:
    runs-on: macos-latest-large
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: danteissaias
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build and Deploy
        env:
          CACHIX_ACTIVATE_TOKEN: ${{ secrets.CACHIX_ACTIVATE_TOKEN }}
        run: |
          cachix deploy activate $(nix build --print-out-paths)
