name: "Deploy"
on:
  pull_request:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: danteissaias
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: echo "DEPLOY_SPEC=$(nix build --print-out-paths)" >> $GITHUB_ENV
      - name: Deploy
        env:
          CACHIX_ACTIVATE_TOKEN: ${{ secrets.CACHIX_ACTIVATE_TOKEN }}
        run: |
          cachix deploy activate deploy.json
