name: "Update"
on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC every day
  workflow_dispatch:
jobs:
  update:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Update flake.lock
        run: |
          nix flake update
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add flake.lock
          git commit -m "chore: update flake.lock" || exit 0
          git push
